# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  ENV_SECRET: ${{ secrets.FLOOD_NOTIFICATIONS_PRODUCER_SECRET }}

jobs:
  build:

    runs-on: ubuntu-24.04

    services:
      rabbitmq:
        image: rabbitmq:4-management
        ports:
          - 5672:5672

    strategy:
      matrix:
        redis-version: [8]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: ${{ matrix.redis-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create .env file
      run: echo "${{ env.ENV_SECRET }}" > .env
        
    - name: Test with pytest
      run: |
        pytest
